### PR TITLE
hook the views 

### PR DESCRIPTION
**Pull request by tenpura-shrimp**
seems like you have to hook the views too

### CODE REVIEW

**Comment by VarunS2002** [comment]
@tenpura-shrimp Which app is this useful in?

**Comment by tenpura-shrimp** [comment]
telegram

**Comment by VarunS2002** [comment]
@tenpura-shrimp telegram secret chat?

**Comment by VarunS2002** [comment]
@tenpura-shrimp which xposed do you use?
I'm making my own version of this app which is up to date
Willing to test it?

**Comment by veeti** [comment]
Thanks for the PR! I don't think I have the signing keys for this anymore, so it's best if you publish your own fork.

**Comment by VarunS2002** [comment]
@veeti @tenpura-shrimp 
https://github.com/VarunS2002/Xposed-Disable-FLAG_SECURE
Latest version
I'll be releasing the apk and publish it on the xposed module repo soon

**Comment by VarunS2002** [comment]
@veeti Major thanks to you!

**Pull request closed without merging**
